site_name: {{ cookiecutter.package_name }}
site_url: 
site_description: Docs for {{ cookiecutter.description }}
site_footer: 
site_author: {{ cookiecutter.author_name }}

copyright: Copyright © 2022 {{ cookiecutter.author_name }} All Rights Reserved.

repo_name: {{ cookiecutter.package_slug }}
repo_url: {{ cookiecutter.repository_url }}

theme:
  logo: assets/logo.svg
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: Helvetica
  name: material
  custom_dir: docs/overrides
  static_templates:
    - 404.html
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)" # 
      scheme: light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 
      scheme: dark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.extra
  - meta

plugins:
  - autorefs
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # show_root_heading: true
            show_object_full_path: true
            show_category_heading: true
            show_if_no_docstring: true
          setup_commands:
            - import os
            - import sys
            - import django
            - sys.path.insert(0, os.path.abspath("."))
            - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "tests.settings")
            - django.setup()
      watch:
        - .
      enable_inventory: true
  - mike:
      canonical_version: "2.7"

nav:
  - Documentation: 
    - Usage:
      - Installation: usage/installation.md
    - Project:
      - Contributing: project/contributing.md
      - Test Fixtures: project/test_fixtures.md
      - Credits: project/authors.md
      - Support: project/support.md
      - Release Process: project/release_process.md
    - Reference:
      - Models: reference/models.md
      - Project: reference/project.md
      - Settings: reference/settings.md
